// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><link rel=\"stylesheet\" href=\"/assets/css/styles.css\"><!-- Ensure HTMX is included --><script src=\"https://unpkg.com/htmx.org\"></script></head><body class=\"bg-white\"><div class=\"relative isolate px-6 pt-14 lg:px-8\"><div class=\"text-center\"><h1 class=\"text-3xl font-bold text-gray-800\">Login</h1><p class=\"text-gray-500\">Login to your account</p></div><div class=\"mt-8\"><form hx-post=\"/users/login\"><div class=\"mb-4\"><label for=\"username\" class=\"block text-sm font-medium text-gray-700\">username</label> <input type=\"text\" name=\"username\" id=\"username\" class=\"w-full px-3 py-2 mt-1 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500\" required></div><div class=\"mb-4\"><label for=\"password\" class=\"block text-sm font-medium text-gray-700\">Password</label> <input type=\"password\" name=\"password\" id=\"password\" class=\"w-full px-3 py-2 mt-1 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500\" required></div><div class=\"mb-4\"><button type=\"submit\" class=\"w-full px-3 py-4 text-white bg-blue-500 rounded-lg\">Login</button></div></form></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
